### ISSUE TITLE
다음 회의까지 할일

### ISSUE THREAD

**Issue by tensorplumber** [cloud2scape/.github#2]
### Discussed in https://github.com/orgs/cloud2scape/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **tensorplumber** October 22, 2024</sup>
조건에 따른 아이디어 구체화 - 멘토에게 얘기할 컨텐츠들

모니터링, 로깅, aws-> 온프렘 이전 고려</div>

**Comment by tensorplumber** [comment]
24/10/23 스몰토크

aws 이전후 복귀까지의 시나리오 고려

iot 공정에서는 서비스가 다운되지 않도록 주요서비스는 온프렘으로 놔둔후 일부만 aws 이전하는 경우가 있음 - 박찬준

각자 지원할 회사에 맞게 기술적 요소를 고려할것

**Comment by pcj1792** [comment]
--10월 28일까지 할일--

1. AI& 동영상과 관련된 서비스 구체화 해오기! 
    (이 부분을 구현할 수 있는지 없는지 궁금하면 재욱님께 질문 ㄱㄱ)

2. 아래 사이트에 들어가서 작성 부탁드립니다! 
    ↓↓↓↓↓↓↓↓↓↓↓↓
   https://www.notion.so/laigasus/b1631720eb9a4979b604039573b86dfa?pvs=4

**Comment by laigasus** [comment]
@pcj1792 회의록은 Discussion 내 토픽을 이용부탁드립니다.
실제 수행 작업물이 있을 때만 issue를 사용합니다(ex 프로그래밍, 설계).

해당 이슈는 삭제될 예정입니다!
감사합니다 🙇
